/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellActivityRouteImport } from './routes/_shell.activity'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellApprovalsRouteImport } from './routes/_shell.approvals'
import { Route as ShellCopilotRouteImport } from './routes/_shell.copilot'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellIntelligenceRouteImport } from './routes/_shell.intelligence'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCookiesRouteImport } from './routes/_site.cookies'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as ShellBookingsIndexRouteImport } from './routes/_shell.bookings.index'
import { Route as ShellBookingsIdRouteImport } from './routes/_shell.bookings.$id'
import { Route as ShellResourcesIndexRouteImport } from './routes/_shell.resources.index'
import { Route as ShellResourcesIdRouteImport } from './routes/_shell.resources.$id'
import { Route as ShellResourcesCompareRouteImport } from './routes/_shell.resources.compare'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellActivityRoute = ShellActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApprovalsRoute = ShellApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCopilotRoute = ShellCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntelligenceRoute = ShellIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCookiesRoute = SiteCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const ShellBookingsIndexRoute = ShellBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBookingsIdRoute = ShellBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResourcesIndexRoute = ShellResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResourcesIdRoute = ShellResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResourcesCompareRoute = ShellResourcesCompareRouteImport.update({
  id: '/resources/compare',
  path: '/resources/compare',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof ShellActivityRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/approvals': typeof ShellApprovalsRoute
  '/copilot': typeof ShellCopilotRoute
  '/dashboard': typeof ShellDashboardRoute
  '/intelligence': typeof ShellIntelligenceRoute
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/settings': typeof ShellSettingsRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/bookings/$id': typeof ShellBookingsIdRoute
  '/resources/$id': typeof ShellResourcesIdRoute
  '/resources/compare': typeof ShellResourcesCompareRoute
  '/bookings/': typeof ShellBookingsIndexRoute
  '/resources/': typeof ShellResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof ShellActivityRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/approvals': typeof ShellApprovalsRoute
  '/copilot': typeof ShellCopilotRoute
  '/dashboard': typeof ShellDashboardRoute
  '/intelligence': typeof ShellIntelligenceRoute
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/settings': typeof ShellSettingsRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/bookings/$id': typeof ShellBookingsIdRoute
  '/resources/$id': typeof ShellResourcesIdRoute
  '/resources/compare': typeof ShellResourcesCompareRoute
  '/bookings': typeof ShellBookingsIndexRoute
  '/resources': typeof ShellResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/activity': typeof ShellActivityRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/approvals': typeof ShellApprovalsRoute
  '/_shell/copilot': typeof ShellCopilotRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/intelligence': typeof ShellIntelligenceRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/cookies': typeof SiteCookiesRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/': typeof SiteIndexRoute
  '/_shell/bookings/$id': typeof ShellBookingsIdRoute
  '/_shell/resources/$id': typeof ShellResourcesIdRoute
  '/_shell/resources/compare': typeof ShellResourcesCompareRoute
  '/_shell/bookings/': typeof ShellBookingsIndexRoute
  '/_shell/resources/': typeof ShellResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/copilot'
    | '/dashboard'
    | '/intelligence'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/bookings/$id'
    | '/resources/$id'
    | '/resources/compare'
    | '/bookings/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/copilot'
    | '/dashboard'
    | '/intelligence'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/bookings/$id'
    | '/resources/$id'
    | '/resources/compare'
    | '/bookings'
    | '/resources'
  id:
    | '__root__'
    | '/_shell'
    | '/_site'
    | '/login'
    | '/_shell/activity'
    | '/_shell/analytics'
    | '/_shell/approvals'
    | '/_shell/copilot'
    | '/_shell/dashboard'
    | '/_shell/intelligence'
    | '/_shell/notifications'
    | '/_shell/profile'
    | '/_shell/settings'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/cookies'
    | '/_site/privacy'
    | '/_site/terms'
    | '/_site/'
    | '/_shell/bookings/$id'
    | '/_shell/resources/$id'
    | '/_shell/resources/compare'
    | '/_shell/bookings/'
    | '/_shell/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/activity': {
      id: '/_shell/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ShellActivityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/approvals': {
      id: '/_shell/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ShellApprovalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/copilot': {
      id: '/_shell/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof ShellCopilotRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/intelligence': {
      id: '/_shell/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof ShellIntelligenceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cookies': {
      id: '/_site/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof SiteCookiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_shell/bookings/': {
      id: '/_shell/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof ShellBookingsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bookings/$id': {
      id: '/_shell/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof ShellBookingsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/resources/': {
      id: '/_shell/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ShellResourcesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/resources/$id': {
      id: '/_shell/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ShellResourcesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/resources/compare': {
      id: '/_shell/resources/compare'
      path: '/resources/compare'
      fullPath: '/resources/compare'
      preLoaderRoute: typeof ShellResourcesCompareRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellActivityRoute: typeof ShellActivityRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellApprovalsRoute: typeof ShellApprovalsRoute
  ShellCopilotRoute: typeof ShellCopilotRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellIntelligenceRoute: typeof ShellIntelligenceRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellBookingsIdRoute: typeof ShellBookingsIdRoute
  ShellResourcesIdRoute: typeof ShellResourcesIdRoute
  ShellResourcesCompareRoute: typeof ShellResourcesCompareRoute
  ShellBookingsIndexRoute: typeof ShellBookingsIndexRoute
  ShellResourcesIndexRoute: typeof ShellResourcesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellActivityRoute: ShellActivityRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellApprovalsRoute: ShellApprovalsRoute,
  ShellCopilotRoute: ShellCopilotRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellIntelligenceRoute: ShellIntelligenceRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellBookingsIdRoute: ShellBookingsIdRoute,
  ShellResourcesIdRoute: ShellResourcesIdRoute,
  ShellResourcesCompareRoute: ShellResourcesCompareRoute,
  ShellBookingsIndexRoute: ShellBookingsIndexRoute,
  ShellResourcesIndexRoute: ShellResourcesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCookiesRoute: typeof SiteCookiesRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCookiesRoute: SiteCookiesRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
